// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-approved-businesses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.23.8";
var list_approved_businesses_default = defineTool({
  name: "list_approved_businesses",
  title: "List approved businesses",
  description: "Return the publicly-listed business profiles from the B.E.E App directory (approved businesses only).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of businesses to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const client = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await client.from("profiles").select("id, business_name, business_category, phone, address, avatar_url").eq("account_type", "business").eq("status", "approved").limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { businesses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_my_profile_default = defineTool2({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's B.E.E App profile (display name, account type, business info, contact fields).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await client.from("profiles").select("id, display_name, account_type, business_name, business_category, phone, address, status, avatar_url, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uadghawuvfzdqomklvha";
var mcp_default = defineMcp({
  name: "bee-app-mcp",
  title: "B.E.E App MCP",
  version: "0.1.0",
  instructions: "Tools for the B.E.E App Bahamas platform. Use `list_approved_businesses` to browse the public business directory. Use `get_my_profile` to read the signed-in user's own profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_approved_businesses_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
